apiVersion: apps/v1
kind: Deployment
metadata:
  name: shazam-api
  namespace: shazam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shazam-api
  template:
    metadata:
      labels:
        app: shazam-api
    spec:
      serviceAccountName: shazam-api
      containers:
      - name: shazam-api
        image: <dockerhub>/shazam-api:latest
        ports:
        - containerPort: 5000
